dataset:
  root: split
  data_root: /home/baole/cmu/2023spring/11785/data/vox1/vox1_all
  batch_size: 64

model:
  name: mi
  args:
    encoder:
      pretrain: true
      args:
        source: speechbrain/spkrec-ecapa-voxceleb
    classifier:
      name: mlp
      args:
        n_input: 192
        layers: [ 256, 256 ]
        activation: ReLU
        dropout: 0.2

optimizer:
  name: AdamW
  args:
    lr: 0.001

epoch_max: 20
scheduler:
  name: CosineAnnealingLR
  args:
    T_max: 20
    eta_min: 0.0001

epoch_save: 10
precision: full
